// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package service

import (
	"context"
	"time"

	"github.com/ijalalfrz/flight-search-aggregation-service/internal/app/dto"
	mock "github.com/stretchr/testify/mock"
)

// NewMockFlightCacher creates a new instance of MockFlightCacher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFlightCacher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFlightCacher {
	mock := &MockFlightCacher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFlightCacher is an autogenerated mock type for the FlightCacher type
type MockFlightCacher struct {
	mock.Mock
}

type MockFlightCacher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFlightCacher) EXPECT() *MockFlightCacher_Expecter {
	return &MockFlightCacher_Expecter{mock: &_m.Mock}
}

// AcquireLock provides a mock function for the type MockFlightCacher
func (_mock *MockFlightCacher) AcquireLock(ctx context.Context, key string, timeout time.Duration) (bool, error) {
	ret := _mock.Called(ctx, key, timeout)

	if len(ret) == 0 {
		panic("no return value specified for AcquireLock")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Duration) (bool, error)); ok {
		return returnFunc(ctx, key, timeout)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Duration) bool); ok {
		r0 = returnFunc(ctx, key, timeout)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, time.Duration) error); ok {
		r1 = returnFunc(ctx, key, timeout)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFlightCacher_AcquireLock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AcquireLock'
type MockFlightCacher_AcquireLock_Call struct {
	*mock.Call
}

// AcquireLock is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - timeout time.Duration
func (_e *MockFlightCacher_Expecter) AcquireLock(ctx interface{}, key interface{}, timeout interface{}) *MockFlightCacher_AcquireLock_Call {
	return &MockFlightCacher_AcquireLock_Call{Call: _e.mock.On("AcquireLock", ctx, key, timeout)}
}

func (_c *MockFlightCacher_AcquireLock_Call) Run(run func(ctx context.Context, key string, timeout time.Duration)) *MockFlightCacher_AcquireLock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 time.Duration
		if args[2] != nil {
			arg2 = args[2].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockFlightCacher_AcquireLock_Call) Return(b bool, err error) *MockFlightCacher_AcquireLock_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockFlightCacher_AcquireLock_Call) RunAndReturn(run func(ctx context.Context, key string, timeout time.Duration) (bool, error)) *MockFlightCacher_AcquireLock_Call {
	_c.Call.Return(run)
	return _c
}

// GetCacheKey provides a mock function for the type MockFlightCacher
func (_mock *MockFlightCacher) GetCacheKey(req dto.SearchCriteria) string {
	ret := _mock.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for GetCacheKey")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(dto.SearchCriteria) string); ok {
		r0 = returnFunc(req)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockFlightCacher_GetCacheKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCacheKey'
type MockFlightCacher_GetCacheKey_Call struct {
	*mock.Call
}

// GetCacheKey is a helper method to define mock.On call
//   - req dto.SearchCriteria
func (_e *MockFlightCacher_Expecter) GetCacheKey(req interface{}) *MockFlightCacher_GetCacheKey_Call {
	return &MockFlightCacher_GetCacheKey_Call{Call: _e.mock.On("GetCacheKey", req)}
}

func (_c *MockFlightCacher_GetCacheKey_Call) Run(run func(req dto.SearchCriteria)) *MockFlightCacher_GetCacheKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 dto.SearchCriteria
		if args[0] != nil {
			arg0 = args[0].(dto.SearchCriteria)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFlightCacher_GetCacheKey_Call) Return(s string) *MockFlightCacher_GetCacheKey_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockFlightCacher_GetCacheKey_Call) RunAndReturn(run func(req dto.SearchCriteria) string) *MockFlightCacher_GetCacheKey_Call {
	_c.Call.Return(run)
	return _c
}

// GetFlight provides a mock function for the type MockFlightCacher
func (_mock *MockFlightCacher) GetFlight(ctx context.Context, key string) ([]dto.Flight, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for GetFlight")
	}

	var r0 []dto.Flight
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]dto.Flight, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []dto.Flight); ok {
		r0 = returnFunc(ctx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.Flight)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFlightCacher_GetFlight_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFlight'
type MockFlightCacher_GetFlight_Call struct {
	*mock.Call
}

// GetFlight is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockFlightCacher_Expecter) GetFlight(ctx interface{}, key interface{}) *MockFlightCacher_GetFlight_Call {
	return &MockFlightCacher_GetFlight_Call{Call: _e.mock.On("GetFlight", ctx, key)}
}

func (_c *MockFlightCacher_GetFlight_Call) Run(run func(ctx context.Context, key string)) *MockFlightCacher_GetFlight_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFlightCacher_GetFlight_Call) Return(flights []dto.Flight, err error) *MockFlightCacher_GetFlight_Call {
	_c.Call.Return(flights, err)
	return _c
}

func (_c *MockFlightCacher_GetFlight_Call) RunAndReturn(run func(ctx context.Context, key string) ([]dto.Flight, error)) *MockFlightCacher_GetFlight_Call {
	_c.Call.Return(run)
	return _c
}

// GetLockKey provides a mock function for the type MockFlightCacher
func (_mock *MockFlightCacher) GetLockKey(req dto.SearchCriteria) string {
	ret := _mock.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for GetLockKey")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(dto.SearchCriteria) string); ok {
		r0 = returnFunc(req)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockFlightCacher_GetLockKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLockKey'
type MockFlightCacher_GetLockKey_Call struct {
	*mock.Call
}

// GetLockKey is a helper method to define mock.On call
//   - req dto.SearchCriteria
func (_e *MockFlightCacher_Expecter) GetLockKey(req interface{}) *MockFlightCacher_GetLockKey_Call {
	return &MockFlightCacher_GetLockKey_Call{Call: _e.mock.On("GetLockKey", req)}
}

func (_c *MockFlightCacher_GetLockKey_Call) Run(run func(req dto.SearchCriteria)) *MockFlightCacher_GetLockKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 dto.SearchCriteria
		if args[0] != nil {
			arg0 = args[0].(dto.SearchCriteria)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFlightCacher_GetLockKey_Call) Return(s string) *MockFlightCacher_GetLockKey_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockFlightCacher_GetLockKey_Call) RunAndReturn(run func(req dto.SearchCriteria) string) *MockFlightCacher_GetLockKey_Call {
	_c.Call.Return(run)
	return _c
}

// GetMetadata provides a mock function for the type MockFlightCacher
func (_mock *MockFlightCacher) GetMetadata(ctx context.Context, key string) (dto.Metadata, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for GetMetadata")
	}

	var r0 dto.Metadata
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (dto.Metadata, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) dto.Metadata); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Get(0).(dto.Metadata)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFlightCacher_GetMetadata_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMetadata'
type MockFlightCacher_GetMetadata_Call struct {
	*mock.Call
}

// GetMetadata is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockFlightCacher_Expecter) GetMetadata(ctx interface{}, key interface{}) *MockFlightCacher_GetMetadata_Call {
	return &MockFlightCacher_GetMetadata_Call{Call: _e.mock.On("GetMetadata", ctx, key)}
}

func (_c *MockFlightCacher_GetMetadata_Call) Run(run func(ctx context.Context, key string)) *MockFlightCacher_GetMetadata_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFlightCacher_GetMetadata_Call) Return(metadata dto.Metadata, err error) *MockFlightCacher_GetMetadata_Call {
	_c.Call.Return(metadata, err)
	return _c
}

func (_c *MockFlightCacher_GetMetadata_Call) RunAndReturn(run func(ctx context.Context, key string) (dto.Metadata, error)) *MockFlightCacher_GetMetadata_Call {
	_c.Call.Return(run)
	return _c
}

// ReleaseLock provides a mock function for the type MockFlightCacher
func (_mock *MockFlightCacher) ReleaseLock(ctx context.Context, key string) error {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for ReleaseLock")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFlightCacher_ReleaseLock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReleaseLock'
type MockFlightCacher_ReleaseLock_Call struct {
	*mock.Call
}

// ReleaseLock is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockFlightCacher_Expecter) ReleaseLock(ctx interface{}, key interface{}) *MockFlightCacher_ReleaseLock_Call {
	return &MockFlightCacher_ReleaseLock_Call{Call: _e.mock.On("ReleaseLock", ctx, key)}
}

func (_c *MockFlightCacher_ReleaseLock_Call) Run(run func(ctx context.Context, key string)) *MockFlightCacher_ReleaseLock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFlightCacher_ReleaseLock_Call) Return(err error) *MockFlightCacher_ReleaseLock_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFlightCacher_ReleaseLock_Call) RunAndReturn(run func(ctx context.Context, key string) error) *MockFlightCacher_ReleaseLock_Call {
	_c.Call.Return(run)
	return _c
}

// SetFlight provides a mock function for the type MockFlightCacher
func (_mock *MockFlightCacher) SetFlight(ctx context.Context, key string, flights []dto.Flight, metadata dto.Metadata, expiration time.Duration) error {
	ret := _mock.Called(ctx, key, flights, metadata, expiration)

	if len(ret) == 0 {
		panic("no return value specified for SetFlight")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []dto.Flight, dto.Metadata, time.Duration) error); ok {
		r0 = returnFunc(ctx, key, flights, metadata, expiration)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFlightCacher_SetFlight_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetFlight'
type MockFlightCacher_SetFlight_Call struct {
	*mock.Call
}

// SetFlight is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - flights []dto.Flight
//   - metadata dto.Metadata
//   - expiration time.Duration
func (_e *MockFlightCacher_Expecter) SetFlight(ctx interface{}, key interface{}, flights interface{}, metadata interface{}, expiration interface{}) *MockFlightCacher_SetFlight_Call {
	return &MockFlightCacher_SetFlight_Call{Call: _e.mock.On("SetFlight", ctx, key, flights, metadata, expiration)}
}

func (_c *MockFlightCacher_SetFlight_Call) Run(run func(ctx context.Context, key string, flights []dto.Flight, metadata dto.Metadata, expiration time.Duration)) *MockFlightCacher_SetFlight_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []dto.Flight
		if args[2] != nil {
			arg2 = args[2].([]dto.Flight)
		}
		var arg3 dto.Metadata
		if args[3] != nil {
			arg3 = args[3].(dto.Metadata)
		}
		var arg4 time.Duration
		if args[4] != nil {
			arg4 = args[4].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockFlightCacher_SetFlight_Call) Return(err error) *MockFlightCacher_SetFlight_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFlightCacher_SetFlight_Call) RunAndReturn(run func(ctx context.Context, key string, flights []dto.Flight, metadata dto.Metadata, expiration time.Duration) error) *MockFlightCacher_SetFlight_Call {
	_c.Call.Return(run)
	return _c
}
