// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package flightprovider

import (
	"context"

	"github.com/ijalalfrz/flight-search-aggregation-service/internal/app/dto"
	mock "github.com/stretchr/testify/mock"
)

// NewMockFlightProvider creates a new instance of MockFlightProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFlightProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFlightProvider {
	mock := &MockFlightProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFlightProvider is an autogenerated mock type for the FlightProvider type
type MockFlightProvider struct {
	mock.Mock
}

type MockFlightProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFlightProvider) EXPECT() *MockFlightProvider_Expecter {
	return &MockFlightProvider_Expecter{mock: &_m.Mock}
}

// Search provides a mock function for the type MockFlightProvider
func (_mock *MockFlightProvider) Search(ctx context.Context, criteria dto.SearchCriteria) ([]dto.Flight, error) {
	ret := _mock.Called(ctx, criteria)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 []dto.Flight
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.SearchCriteria) ([]dto.Flight, error)); ok {
		return returnFunc(ctx, criteria)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.SearchCriteria) []dto.Flight); ok {
		r0 = returnFunc(ctx, criteria)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dto.Flight)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, dto.SearchCriteria) error); ok {
		r1 = returnFunc(ctx, criteria)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFlightProvider_Search_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Search'
type MockFlightProvider_Search_Call struct {
	*mock.Call
}

// Search is a helper method to define mock.On call
//   - ctx context.Context
//   - criteria dto.SearchCriteria
func (_e *MockFlightProvider_Expecter) Search(ctx interface{}, criteria interface{}) *MockFlightProvider_Search_Call {
	return &MockFlightProvider_Search_Call{Call: _e.mock.On("Search", ctx, criteria)}
}

func (_c *MockFlightProvider_Search_Call) Run(run func(ctx context.Context, criteria dto.SearchCriteria)) *MockFlightProvider_Search_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 dto.SearchCriteria
		if args[1] != nil {
			arg1 = args[1].(dto.SearchCriteria)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFlightProvider_Search_Call) Return(flights []dto.Flight, err error) *MockFlightProvider_Search_Call {
	_c.Call.Return(flights, err)
	return _c
}

func (_c *MockFlightProvider_Search_Call) RunAndReturn(run func(ctx context.Context, criteria dto.SearchCriteria) ([]dto.Flight, error)) *MockFlightProvider_Search_Call {
	_c.Call.Return(run)
	return _c
}
